#ifndef YQ_RESOURCE_H
#define YQ_RESOURCE_H

#define IDD_YQ_VIDEO_DIALOG 100
#define IDC_YQ_VIDEO_DIALOG_OPEN 101
#define IDC_YQ_VIDEO_DIALOG_PLAY 102
#define IDC_YQ_VIDEO_DIALOG_STOP 103
#define IDC_YQ_VIDEO_DIALOG_TRACKBAR 104
#define IDS_YQ_VIDEO_DIALOG_MASK_OPEN 105
#define IDC_YQ_VIDEO_CONTROL 106
#define IDS_YQ_ERROR_MSG 107

#endif //YQ_RESOURCE_H
