#ifndef YQ_RESOURCE_H
#define YQ_RESOURCE_H

#define IDC_YQ_IMAGE_WINDOW 100
#define IDS_YQ_IMAGE_WINDOW_TITLE 101
#define IDM_YQ_IMAGE_WINDOW_OPEN 102
#define IDM_YQ_IMAGE_WINDOW_SAVE_AS 103
#define IDM_YQ_IMAGE_WINDOW_FLIP_X 105
#define IDM_YQ_IMAGE_WINDOW_FLIP_Y 106
#define IDM_YQ_IMAGE_WINDOW_INVERT_R 107
#define IDM_YQ_IMAGE_WINDOW_INVERT_G 108
#define IDM_YQ_IMAGE_WINDOW_INVERT_B 109
#define IDS_YQ_IMAGE_WINDOW_MASK_OPEN 110
#define IDS_YQ_IMAGE_WINDOW_MASK_SAVE 111
#define IDS_YQ_IMAGE_WINDOW_ERROR_MSG 112

#endif //YQ_RESOURCE_H
